spring.application.name=Office-booking-system
spring.datasource.url=jdbc:mysql://localhost:3306/office_booking
spring.datasource.username=officeuser
spring.datasource.password=office123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true